id: P010708
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4323
  title: གསུང་འབུམ། སངས་རྒྱས་ཕུན་ཚོགས་
  author: ''
  volumes:
    72ebae9b0d914766bc24eed5ee0d4844:
      image_group_id: I1KG4380
      title: ''
      volume_number: 1
      total_pages: 694
      base_file: v001.txt
