id: P010708
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:53.940761
source_metadata:
  id: bdr:W1KG4323
  title: གསུང་འབུམ། སངས་རྒྱས་ཕུན་ཚོགས་
  author: ''
  volumes:
    72ebae9b0d914766bc24eed5ee0d4844:
      image_group_id: I1KG4380
      title: ''
      volume_number: 1
      total_pages: 694
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
