id: I25E56A91
legacy_id: P010708
ocr_import_info:
  bdrc_scan_id: W1KG4323
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T13:56:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:27:55.719077+00:00'
last_modified: 2022-09-01 00:28:14.873212
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4323
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4323
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སངས་རྒྱས་ཕུན་ཚོགས།
  author: ངོར་མཁན་ཆེན ༢༥་སངས་རྒྱས་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.9363573936932122
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG4380:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4380
      total_pages: 694
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4380.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9363573936932122
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
